

services:
  db:
    image: postgres:15-alpine
    container_name: blog_postgres
    environment:
      POSTGRES_USER: shamil
      POSTGRES_PASSWORD: Shamil1234
      POSTGRES_DB: blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamil -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: blog_app
    command: sh -c "python run_migrations.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # ВАЖНО: Здесь мы явно указываем, что хост базы данных - это сервис 'db'
      - POSTGRES_USER=shamil
      - POSTGRES_PASSWORD=Shamil1234
      - POSTGRES_DB=blog_db
      - POSTGRES_HOST=db            # ← ← ← ЭТО ДОЛЖНО БЫТЬ 'db', а не 'localhost'!
      - POSTGRES_PORT=5432
      - SECRET_KEY=super-secret-key-change-in-production-12345
      - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: