"""Add rating field to Post

Revision ID: 761de06b43fe
Revises: 214ce53f38c2
Create Date: 2026-03-26 19:50:04.472028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761de06b43fe'
down_revision: Union[str, Sequence[str], None] = '214ce53f38c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    op.add_column('categories', sa.Column('icon', sa.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
